// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJKZb8qis4wbYq4z1CUhmSTFTNCfhXLII',
    appId: '1:548125942723:web:714e6c9da93224c48d5376',
    messagingSenderId: '548125942723',
    projectId: 'eventosciudadapp',
    authDomain: 'eventosciudadapp.firebaseapp.com',
    storageBucket: 'eventosciudadapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSOuyB7BHAxM78VHXuMZw974OyjSfQps',
    appId: '1:548125942723:android:acd5bedeec26a2b68d5376',
    messagingSenderId: '548125942723',
    projectId: 'eventosciudadapp',
    storageBucket: 'eventosciudadapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUWnuLqReVZi9p76Ov4BRUcwVcdgz-pM',
    appId: '1:548125942723:ios:75b93f87334b2eab8d5376',
    messagingSenderId: '548125942723',
    projectId: 'eventosciudadapp',
    storageBucket: 'eventosciudadapp.firebasestorage.app',
    iosBundleId: 'com.example.appTurista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUWnuLqReVZi9p76Ov4BRUcwVcdgz-pM',
    appId: '1:548125942723:ios:75b93f87334b2eab8d5376',
    messagingSenderId: '548125942723',
    projectId: 'eventosciudadapp',
    storageBucket: 'eventosciudadapp.firebasestorage.app',
    iosBundleId: 'com.example.appTurista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJKZb8qis4wbYq4z1CUhmSTFTNCfhXLII',
    appId: '1:548125942723:web:3f5087e263ca1d168d5376',
    messagingSenderId: '548125942723',
    projectId: 'eventosciudadapp',
    authDomain: 'eventosciudadapp.firebaseapp.com',
    storageBucket: 'eventosciudadapp.firebasestorage.app',
  );
}
